### ISSUE TITLE
[Satosa Backend] Trust layer abstraction and extensions

### ISSUE THREAD

**Issue by peppelinux** [italia/eudi-wallet-it-python#267]
## Requirements

Implementers ...

- The trust layer should be handled with a neutral member nbame, including several other trust evaluation mechanisms. See poi 1 below.
- MUST be able to define their own Classes/Packages and include these within the trust configuration of the satosa backend

## Point 1
The current satosa backend configuration is OpenID Federation driven, see below: 

````
  federation:
    metadata_type: "wallet_relying_party"
    authority_hints:
        - http://127.0.0.1:8000
    trust_anchors:
        - http://127.0.0.1:8000
    default_sig_alg: "RS256"
    federation_entity_metadata:
        organization_name: Developers Italia SATOSA OpenID4VP backend
        homepage_uri: https://developers.italia.it
        policy_uri: https://developers.italia.it
        tos_uri: https://developers.italia.it
        logo_uri: https://developers.italia.it/assets/icons/logo-it.svg
````

We should generalize in this way

````
    trust:
      federation:
        module: $ClassNameModulePath
        class: $ClassName
        config:
            metadata_type: "openid_credential_verifier"
            authority_hints:
                - http://127.0.0.1:8000
            trust_anchors:
                - public_keys: [ ... ]
                - http://127.0.0.1:8000
            default_sig_alg: "RS256"
            federation_entity_metadata:
                organization_name: Developers Italia SATOSA OpenID4VP backend
                homepage_uri: https://developers.italia.it
                policy_uri: https://developers.italia.it
                tos_uri: https://developers.italia.it
                logo_uri: https://developers.italia.it/assets/icons/logo-it.svg
      x509:
        module: $ClassNameModulePath
        class: $ClassName
        config:
            trust_anchor_certificates: [ ... ]
            trust_anchors_cn: # we might mix CN and SAN together
                - http://127.0.0.1:8000
      direct_trust:
        module: $ClassNameModulePath
        class: $ClassName
        config:
            well_known_metadata_endpoints: [...]
      did_x509:
        module: $ClassNameModulePath
        class: $ClassName
      did_xyz:
        module: $ClassNameModulePath
        class: $ClassName
````
