### ISSUE TITLE
[Response Endpoint] Verify Credentials providing static x5c to Trust Evaluator

### ISSUE THREAD

**Issue by peppelinux** [italia/eudi-wallet-it-python#392]
TrustParameterData must be renamed to TrustEvaluationType

moreover, here:
https://github.com/italia/eudi-wallet-it-python/blob/2fa16a74241e343de340c076a7d1d875a0fd5f48/pyeudiw/trust/dynamic.py#L157

`self.trust_evaluator.get_public_keys(token_issuer)`:

- must take also the static cryptographic material obtained from the parsed credentials
- must validate the keys (and upsert them into the db) using the CA public keys

CA public keys must be stored within a local folder, and referenced in the configuration in this way:

````
    x509:
      module: pyeudiw.trust.handler.x509
      class: X509TrustHandler
      config:
        client_id: *client_id
        client_id_scheme: x509_san_dns # this will be prepended in the client id scheme used in the request. 
        relying_party_certificate_chains_by_ca: # chains can be formed by items serialized in binary python serialization or PEM
            - ca.example.com: 
              - !!binary ....
        private_keys: *metadata_jwks
        ca_certificates_path: /path/to/x5c/PEM/about/trusted/CAs
````

when we init the x509 trust handler, all the valid (unexpired/unrevoked) certificates must be loaded (upserted) into the DB (see: https://github.com/italia/eudi-wallet-it-python/blob/dev/docs/STORAGE.md#trust-anchors)

therefore, `self.trust_evaluator.get_public_keys(token_issuer, static_trust_materials={"x5c" ... "trust_chain" ...})` must recognize the x509 chain (or static federation trust chain ...), its CA and check that the cruptographic material about that CA is aligned with those into the DB, therefore the material into the DB will be used to validate the chain, upsert the key about that issuer into the DB and return the valid criptographic key.

notes:

from a chain:

1. extract the CA identifier
2. check if we have it in the DB, if not -> it is not trusted
3. check that the crypto key derived from the certificate is present into the DB about that CA identifier (to facilitate that, you might think to use a thumbprint value)
