### ISSUE TITLE
Update of JAR header is broken when custom client_id used

### ISSUE THREAD

**Issue by Zicchio** [italia/eudi-wallet-it-python#412]
When using a configuration with a custom client id (such as formerly required by Potential, where for example we use IT-TNDIGT-RP), this methods breaks down and raises an exception
https://github.com/italia/eudi-wallet-it-python/blob/e2454c5265fee98fd4b9dc5fabcf147fe3cdfa31/pyeudiw/trust/dynamic.py#L299

In particular, it fails when trying to build the header claim for the direct trust module (which I guess should be empty because as fair as I know direct trust is not associated to any header claim)

**Comment by PascalDR** [comment]
@Zicchio can you add the exception raised?
Can you also share an example configuration or some steps to reproduce the issue?

**Comment by Zicchio** [comment]
Sure.

Version tested e2454c5265fee98fd4b9dc5fabcf147fe3cdfa31

This is the configuration file of the backend module

```
module: pyeudiw.satosa.backend.OpenID4VPBackend
name: OpenID4VP

config:

  ui:
    static_storage_url: !ENV SATOSA_BASE_STATIC
    template_folder: "templates" # project root
    qrcode_template: "qr_code.html"
    error_template: "error.html"
    error_url: "https://localhost/error_page.html"
    authorization_error_template: "authorization_error.html"
  
  endpoints:
    pre_request: '/pre-request'
    request:
      module: pyeudiw.satosa.default.request_handler
      class: RequestHandler
      path: '/request-uri'
    response:
      module: pyeudiw.satosa.default.response_handler
      class: ResponseHandler
      path: '/response-uri'
    status: '/status'
    get_response: '/get-response'

  qrcode:
    size: 250 # px
    color: '#000000'  # hex
    expiration_time: 120 # seconds
    logo_path: 'wallet-it/wallet-icon-blue.svg' # relative to static_storage_url

  response_code:
    sym_key: "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef" # hex string of 64 characters

  jwt:
    default_sig_alg: ES256 # or RS256. Please note that this signature alg MUST be compliant with the private keys used for the signature. X.509 certificates MUST be therefore ECDSA using ES, and RSA using RS
    default_enc_alg: RSA-OAEP
    default_enc_enc: A256CBC-HS512
    default_exp: 6         # minutes
    enc_alg_supported: &enc_alg_supported
        - RSA-OAEP
        - RSA-OAEP-256
        - ECDH-ES
        - ECDH-ES+A128KW
        - ECDH-ES+A192KW
        - ECDH-ES+A256KW
    enc_enc_supported: &enc_enc_supported
        - A128CBC-HS256
        - A192CBC-HS384
        - A256CBC-HS512
        - A128GCM
        - A192GCM
        - A256GCM
    sig_alg_supported: &sig_alg_supported
        - RS256
        - RS384
        - RS512
        - ES256
        - ES384
        - ES512
    
  authorization:
    client_id: IT-RP
    auth_iss_id: # this field if not set will be set to client_id in the authz request 
    url_scheme: haip
    scopes:
    - pid-sd-jwt:unique_id+given_name+family_name
    default_acr_value: https://www.spid.gov.it/SpidL2
    expiration_time: 5 # minutes
    aud: https://self-issued.me/v2
    response_mode: direct_post
    presentation_definition:
      id: global-presentation-definition-id
      input_descriptors:
      - id: input-specific-id
        purpose: Request presentation holding Power of Representation attestation
        format:
          dc+sd-jwt: {}
        constraints:
          fields:
          - path:
            - "$.vct"
            filter:
              const: urn:eu.europa.ec.eudi:por:1
      - id: another-input-specific-id
        purpose: Request first name and last name claims from PID attestation
        format:
          dc+sd-jwt: {}
        constraints:
          limit_disclosure: required
          fields:
            - path:
              - "$.vct"
              filter:
                type: string
                pattern: urn:eu.europa.ec.eudi:por:1
            - path:
              - "$.family_name"
            - path:
              - "$.given_name"

  user_attributes:
    unique_identifiers:
    - tax_id_code
    - unique_id
    subject_id_random_value: CHANGEME!
  
  network:
    httpc_params: &httpc_params
      connection:
        ssl: true
      session:
        timeout: 6

  # private jwk
  metadata_jwks: &metadata_jwks
    - crv: P-256 # Please note: this is the first key [0] and it is used for signing the presentation requests
      d: KzQBowMMoPmSZe7G8QsdEWc1IvR2nsgE8qTOYmMcLtc
      kid: dDwPWXz5sCtczj7CJbqgPGJ2qQ83gZ9Sfs-tJyULi6s
      use: sig
      kty: EC
      x: TSO-KOqdnUj5SUuasdlRB2VVFSqtJOxuR5GftUTuBdk
      y: ByWgQt1wGBSnF56jQqLdoO1xKUynMY-BHIDB3eXlR7
    - kty: RSA
      d: QUZsh1NqvpueootsdSjFQz-BUvxwd3Qnzm5qNb-WeOsvt3rWMEv0Q8CZrla2tndHTJhwioo1U4NuQey7znijhZ177bUwPPxSW1r68dEnL2U74nKwwoYeeMdEXnUfZSPxzs7nY6b7vtyCoA-AjiVYFOlgKNAItspv1HxeyGCLhLYhKvS_YoTdAeLuegETU5D6K1xGQIuw0nS13Icjz79Y8jC10TX4FdZwdX-NmuIEDP5-s95V9DMENtVqJAVE3L-wO-NdDilyjyOmAbntgsCzYVGH9U3W_djh4t3qVFCv3r0S-DA2FD3THvlrFi655L0QHR3gu_Fbj3b9Ybtajpue_Q
      e: AQAB
      use: enc
      kid: 9Cquk0X-fNPSdePQIgQcQZtD6J0IjIRrFigW2PPK_-w
      n: utqtxbs-jnK0cPsV7aRkkZKA9t4S-WSZa3nCZtYIKDpgLnR_qcpeF0diJZvKOqXmj2cXaKFUE-8uHKAHo7BL7T-Rj2x3vGESh7SG1pE0thDGlXj4yNsg0qNvCXtk703L2H3i1UXwx6nq1uFxD2EcOE4a6qDYBI16Zl71TUZktJwmOejoHl16CPWqDLGo9GUSk_MmHOV20m4wXWkB4qbvpWVY8H6b2a0rB1B1YPOs5ZLYarSYZgjDEg6DMtZ4NgiwZ-4N1aaLwyO-GLwt9Vf-NBKwoxeRyD3zWE2FXRFBbhKGksMrCGnFDsNl5JTlPjaM3kYyImE941ggcuc495m-Fw
      p: 2zmGXIMCEHPphw778YjVTar1eycih6fFSJ4I4bl1iq167GqO0PjlOx6CZ1-OdBTVU7HfrYRiUK_BnGRdPDn-DQghwwkB79ZdHWL14wXnpB5y-boHz_LxvjsEqXtuQYcIkidOGaMG68XNT1nM4F9a8UKFr5hHYT5_UIQSwsxlRQ0
      q: 2jMFt2iFrdaYabdXuB4QMboVjPvbLA-IVb6_0hSG_-EueGBvgcBxdFGIZaG6kqHqlB7qMsSzdptU0vn6IgmCZnX-Hlt6c5X7JB_q91PZMLTO01pbZ2Bk58GloalCHnw_mjPh0YPviH5jGoWM5RHyl_HDDMI-UeLkzP7ImxGizrM
    - kty: RSA
      use: sig
      alg: RS256
      kid: m00NPAelNBnG_wK2R5EpI_k-GWCHEUySamQYubgFjCg
      d: nMsnqz0lPHNGBgUqyuJ5nXQ0jh-mzs6d2xOY_QhpkRW1kEbexRJDdVV3fqMxj_s0MiF8mn-s8ea3e8cbNDgIy000Wvx05y1rMkB6KaZX2ZL5jwU7i_xP6NlLh8itikqJz7kKQSILgibQFFQDcScpEk8gUKa6fmSJQVwTII6GoJCdiJflv-FI2OQ_TCBQEEVVLpeUiVSP0n3OMUKGBlbaHOQkArUpla_ke_mtdfIrl7uB74Rxrin68KtFHkGDGdJPs-PPO1yJ2paFZI9QR_ettZ22v45c-qIgmCjsEnITDMaO9724PU_umlWsWe36Y9RAAzofKsjKqvA1OIzU03ob9Q
      n: sP6jt1XwJE0JDKxy4B7r3Jdb8W6bSRoVunyjWMgl5IafqFwHsJlYgCAWPeTrAL-iyjdnWC1csHuTqWjdndDL-oqEarrqoDAycVkfFTUTD81_wVhWUzAwxhQHiT7PTUIsV7m9VGlfC_kdCpQl5CcK1yx2nQ1KbqWOV1_5WnMgnN_EpNmztkZDnJmKedVduOb2dKWwnLS3fcGvUxXc87DjAzC2vfgQSoQfXAZbwItyS6OinFiUnBxRvt9ZY2IapjI1-wwDKKeRrqPC-fV2oWTrMqoYAvIDnf9AjKHAbIw7q301-7-eaUMF1hVtAz1XeXvMp0wK8_uSo9Vgv1vHhBpOwQ
      e: AQAB
      p: 0ViKTSyZdLtvbLBpTvVAXTdrhTwGXuh16PadQMAVmkoxOPiExRB5uLiy2ADaVKSglia5aQBUp9v0ygEEOmkiUtn5A26D9ui0dkPR0hx4fwqCOOmA2ZyDUNFJ_qrGSwT1SxGQDHeRteymJG7uN9QekS3XiBDgFJxwl-vVpoSTBJM
      q: 2HBr9qhVd3zZUQuNb7ro06ErLl4fhL-DiKsNqXB772tDNTJYeog1nOWgS22tcv5WHrSoYF1x5Q74YVoA6yVj6DwFx2Hc2pYZazzhYMRC3NAWkTEdroy9IjtpzKIpQIqw-sq8CbWVBXzho8uQBCdg8h73z11_HPyXT9BqQCmxJ9s
      dp: WsQ32rQuqNUnv4lRb4GYcZI41SCsZnQFw4dBsTRXaXknlFr0PfkhvXyfVlYwU6i5U8DgfO0-xzTwErGUIrs4vZFyjRFauDA3JlvLWn0rpXFp-sELM87PhLfpjDiBFz_EFtM7kJw7GhTMCFnsgVpAEpQ8sesXLPiTPNts2_D5SW8
      dq: jWlucLrtFGOjDRuyLjT9l__uWZ4vk6kZRHsWMwWGRBhd0ezx-CT0em1hPMcNE1vvYqKAfG2xU4pjaB_JB9nnG73TvMBI7xwwwWsGihXQ5bqjc_uWPAxCKpKM_qFYuI2lMkaxctqL4gkE1-LRVpVv9uGa4YZh3ct_BSvTr9ZNpA8
      qi: kn9Etj4a2erCUmoZUQalPjHxCRYm5Q3wAkFIRGSQADA51mkwQHyTYqXbHcmXn2ZgXBVI6XDWJB51Me-NCPfITTlusqxvATF7Q-QJtdK_FbgNtcVRNc1FMq_M7VBHA1i9wJR7T4t57aywfXPmlsA5TToTDRe-ybdw0C3ys4KQATs

  #This is the configuration for the relaying party metadata
  metadata: &metadata
    application_type: web

    #The following section contains all the algorithms supported for the encryption of response
    authorization_encrypted_response_alg: *enc_alg_supported
    authorization_encrypted_response_enc: *enc_enc_supported
    authorization_signed_response_alg: *sig_alg_supported

    #Various informations of the client
    client_id: # this field is autopopulated using internal variables base_url and name using the following format: "<base_url>/<name>" 
    client_name: Name of an example organization
    contacts:
      - ops@verifier.example.org
    default_acr_values:
      - https://www.spid.gov.it/SpidL2
      - https://www.spid.gov.it/SpidL3

    #The following section contains all the algorithms supported for the encryption of id token response
    id_token_encrypted_response_alg: *enc_alg_supported
    id_token_encrypted_response_enc: *enc_enc_supported
    id_token_signed_response_alg: *sig_alg_supported

    # public part loaded in the __init__
    jwks: *metadata_jwks

    redirect_uris: 
      # This field is autopopulated using internal variables base_url and name using the following format: <base_url>/<name>/redirect-uri"
    request_uris: 
      # This field is autopopulated using internal variables base_url and name using the following format: <base_url>/<name>/request-uri"

    # not necessary according to openid4vp
    # default_max_age: 1111
    # require_auth_time: true
    # subject_type: pairwise

    vp_formats:
      dc+sd-jwt:
        sd-jwt_alg_values:
          - ES256
          - ES384
        kb-jwt_alg_values:
          - ES256
          - ES384

  credential_presentation_handlers:
    max_submission_size: 4096
    formats:
      - module: pyeudiw.openid4vp.vp_sd_jwt_vc
        class:  VpVcSdJwtParserVerifier
        format: dc+sd-jwt
        config:
          sig_alg_supported: *sig_alg_supported
      # - module: pyeudiw.openid4vp.vp_mdoc_cbor
      #   class:  VpMDocCbor
      #   format: mso_mdoc

  trust:
    direct_trust_sd_jwt_vc:
      module: pyeudiw.trust.handler.direct_trust_sd_jwt_vc
      class: DirectTrustSdJwtVc
      config:
        cache_ttl: 0
        httpc_params: *httpc_params
        jwk_endpoint: /.well-known/jwt-vc-issuer
    direct_trust_jar:
      module: pyeudiw.trust.handler.direct_trust_jar
      class: DirectTrustJar
      config:
        cache_ttl: 0
        httpc_params: *httpc_params
        jwk_endpoint: /.well-known/jar-issuer
        jwks: *metadata_jwks
    federation:
      module: pyeudiw.trust.handler.federation
      class: FederationHandler
      config:
        httpc_params: *httpc_params
        cache_ttl: 0
        entity_configuration_exp: 600
        metadata_type: "openid_credential_verifier"
        metadata: *metadata
        authority_hints:
            - http://127.0.0.1:8000
        trust_anchors:
            - http://127.0.0.1:8000:
              -
            - https://trust-anchor.edu:
              -
            - https://trust-anchor.example.org:
              - kty: RSA
                d: QUZsh1NqvpueootsdSjFQz-BUvxwd3Qnzm5qNb-WeOsvt3rWMEv0Q8CZrla2tndHTJhwioo1U4NuQey7znijhZ177bUwPPxSW1r68dEnL2U74nKwwoYeeMdEXnUfZSPxzs7nY6b7vtyCoA-AjiVYFOlgKNAItspv1HxeyGCLhLYhKvS_YoTdAeLuegETU5D6K1xGQIuw0nS13Icjz79Y8jC10TX4FdZwdX-NmuIEDP5-s95V9DMENtVqJAVE3L-wO-NdDilyjyOmAbntgsCzYVGH9U3W_djh4t3qVFCv3r0S-DA2FD3THvlrFi655L0QHR3gu_Fbj3b9Ybtajpue_Q
                e: AQAB
                kid: 9Cquk0X-fNPSdePQIgQcQZtD6J0IjIRrFigW2PPK_-w
                n: utqtxbs-jnK0cPsV7aRkkZKA9t4S-WSZa3nCZtYIKDpgLnR_qcpeF0diJZvKOqXmj2cXaKFUE-8uHKAHo7BL7T-Rj2x3vGESh7SG1pE0thDGlXj4yNsg0qNvCXtk703L2H3i1UXwx6nq1uFxD2EcOE4a6qDYBI16Zl71TUZktJwmOejoHl16CPWqDLGo9GUSk_MmHOV20m4wXWkB4qbvpWVY8H6b2a0rB1B1YPOs5ZLYarSYZgjDEg6DMtZ4NgiwZ-4N1aaLwyO-GLwt9Vf-NBKwoxeRyD3zWE2FXRFBbhKGksMrCGnFDsNl5JTlPjaM3kYyImE941ggcuc495m-Fw
                p: 2zmGXIMCEHPphw778YjVTar1eycih6fFSJ4I4bl1iq167GqO0PjlOx6CZ1-OdBTVU7HfrYRiUK_BnGRdPDn-DQghwwkB79ZdHWL14wXnpB5y-boHz_LxvjsEqXtuQYcIkidOGaMG68XNT1nM4F9a8UKFr5hHYT5_UIQSwsxlRQ0
                q: 2jMFt2iFrdaYabdXuB4QMboVjPvbLA-IVb6_0hSG_-EueGBvgcBxdFGIZaG6kqHqlB7qMsSzdptU0vn6IgmCZnX-Hlt6c5X7JB_q91PZMLTO01pbZ2Bk58GloalCHnw_mjPh0YPviH5jGoWM5RHyl_HDDMI-UeLkzP7ImxGizrM
        default_sig_alg: "RS256"
        trust_marks: [] 
        federation_entity_metadata:
            organization_name: IAM Proxy Italia OpenID4VP backend
            homepage_uri: https://developers.italia.it
            policy_uri: https://developers.italia.it
            tos_uri: https://developers.italia.it
            logo_uri: https://developers.italia.it/assets/icons/logo-it.svg
        federation_jwks: # !ENV PYEUDIW_FEDERATION_JWKS
          - kty: RSA
            d: QUZsh1NqvpueootsdSjFQz-BUvxwd3Qnzm5qNb-WeOsvt3rWMEv0Q8CZrla2tndHTJhwioo1U4NuQey7znijhZ177bUwPPxSW1r68dEnL2U74nKwwoYeeMdEXnUfZSPxzs7nY6b7vtyCoA-AjiVYFOlgKNAItspv1HxeyGCLhLYhKvS_YoTdAeLuegETU5D6K1xGQIuw0nS13Icjz79Y8jC10TX4FdZwdX-NmuIEDP5-s95V9DMENtVqJAVE3L-wO-NdDilyjyOmAbntgsCzYVGH9U3W_djh4t3qVFCv3r0S-DA2FD3THvlrFi655L0QHR3gu_Fbj3b9Ybtajpue_Q
            e: AQAB
            kid: 9Cquk0X-fNPSdePQIgQcQZtD6J0IjIRrFigW2PPK_-w
            n: utqtxbs-jnK0cPsV7aRkkZKA9t4S-WSZa3nCZtYIKDpgLnR_qcpeF0diJZvKOqXmj2cXaKFUE-8uHKAHo7BL7T-Rj2x3vGESh7SG1pE0thDGlXj4yNsg0qNvCXtk703L2H3i1UXwx6nq1uFxD2EcOE4a6qDYBI16Zl71TUZktJwmOejoHl16CPWqDLGo9GUSk_MmHOV20m4wXWkB4qbvpWVY8H6b2a0rB1B1YPOs5ZLYarSYZgjDEg6DMtZ4NgiwZ-4N1aaLwyO-GLwt9Vf-NBKwoxeRyD3zWE2FXRFBbhKGksMrCGnFDsNl5JTlPjaM3kYyImE941ggcuc495m-Fw
            p: 2zmGXIMCEHPphw778YjVTar1eycih6fFSJ4I4bl1iq167GqO0PjlOx6CZ1-OdBTVU7HfrYRiUK_BnGRdPDn-DQghwwkB79ZdHWL14wXnpB5y-boHz_LxvjsEqXtuQYcIkidOGaMG68XNT1nM4F9a8UKFr5hHYT5_UIQSwsxlRQ0
            q: 2jMFt2iFrdaYabdXuB4QMboVjPvbLA-IVb6_0hSG_-EueGBvgcBxdFGIZaG6kqHqlB7qMsSzdptU0vn6IgmCZnX-Hlt6c5X7JB_q91PZMLTO01pbZ2Bk58GloalCHnw_mjPh0YPviH5jGoWM5RHyl_HDDMI-UeLkzP7ImxGizrM
    # x509:
    #   module: pyeudiw.trust.handler.x509
    #   class: X509Handler
    #   config:
    #     # client_id: *client_id
    #     client_id_scheme: x509_san_dns # this will be prepended in the client id scheme used in the request. 
    #     certificate_authorities:
    #       - ca.example.com: |
    #             -----BEGIN CERTIFICATE-----
    #             MIIDYzCCAkugAwIBAgIUHVMNJD9vqAA4mR+QAJyEQFW4kjQwDQYJKoZIhvcNAQEL
    #             BQAwUjEuMCwGA1UEAwwlQ049Y2EuZXhhbXBsZS5jb20sIE89RXhhbXBsZSBDQSwg
    #             Qz1JVDETMBEGA1UECgwKRXhhbXBsZSBDQTELMAkGA1UEBhMCSVQwHhcNMjUwNDAz
    #             MTU0NzU2WhcNMjYwNDA0MTU0NzU2WjBSMS4wLAYDVQQDDCVDTj1jYS5leGFtcGxl
    #             LmNvbSwgTz1FeGFtcGxlIENBLCBDPUlUMRMwEQYDVQQKDApFeGFtcGxlIENBMQsw
    #             CQYDVQQGEwJJVDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMf3zvlY
    #             zX1DYgv9QjRusMQjSRNdZi72/ydnxO/cAQ1GsgLZ8ewqIL1CnXtIs6i2F8poUOec
    #             g957xk1db6sTqEWXRi5h9IfMUFcd5G7gIbJzjXCiLSVz6m9vZlvqR7BDka1VQhuH
    #             rW2xEIE6+F2lWxJ+crimea/c5VlMKBCh+gQldFq3lTu6smGUz8xl8rhleBPgTgZz
    #             TO4VuVO1dOb/S4lq9twfVYCTznF9vgaNaNh3la7yjzCf+zpSTGQD8TFO8ws1SZRq
    #             O0bkabW8/5XsnwFHLT2LMSPkWMgMD8r+7xef93bvbEy7SA4Hw1Iow2xIIcTDYQ7F
    #             77HQ3OjkogHmhrMCAwEAAaMxMC8wEgYDVR0TAQH/BAgwBgEB/wIBATAZBgNVHREE
    #             EjAQgg5jYS5leGFtcGxlLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEApRUUxw5Dn0wd
    #             lFPApjn7n/SZyx5I1XnOHOIk8aWD0KFFa1zsnONlmRDgC8EQ5XKw3nMUwvnCQUR8
    #             6FmrqP5gINHdqfvWiitC0eQdDhMhIHvdfUMBicgZ0XDVjDZhD6W9A+IWwR3ySLCf
    #             lZHA5JwjYhpAjMYFXwSVZklOre34zJL6CRwgIUKjc9uyGPmlnVRFTUcUqLB9Uq/U
    #             dFc7XMPBAbMt1frOJRj6P1OFtubuC0INpEhzivg3+w8bXmpEN6e2hBvIjoNkgnWF
    #             O6HVbDnJXTA34/I4snisJfZQ+Z9gln921+2Q27sMvyS7aBqtocDuWB0w3XZ3aCYk
    #             DTEzMjUtQA==
    #             -----END CERTIFICATE-----
    #     relying_party_certificate_chains_by_ca: # X.509 chains in PEM format. Please note: Leaf's certificate MUST be related to metadata_jwks[0]
    #         ca.example.com:
    #           - |
    #             -----BEGIN CERTIFICATE-----
    #             MIIDfzCCAmegAwIBAgIUN3niXMK8XOjhIvf6EUD4sz80XIkwDQYJKoZIhvcNAQEL
    #             BQAwTjEpMCcGA1UEAwwgaHR0cHM6Ly9pbnRlcm1lZGlhdGUuZXhhbXBsZS5uZXQx
    #             FDASBgNVBAoMC0V4YW1wbGUgSU5UMQswCQYDVQQGEwJJVDAeFw0yNTA0MDMxNTQ3
    #             NTZaFw0yNjA0MDQxNTQ3NTZaMFcxMTAvBgNVBAMMKENOPWVhZi5leGFtcGxlLmNv
    #             bSwgTz1FeGFtcGxlIExlYWYsIEM9SVQxFTATBgNVBAoMDEV4YW1wbGUgTGVhZjEL
    #             MAkGA1UEBhMCSVQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCw/qO3
    #             VfAkTQkMrHLgHuvcl1vxbptJGhW6fKNYyCXkhp+oXAewmViAIBY95OsAv6LKN2dY
    #             LVywe5OpaN2d0Mv6ioRquuqgMDJxWR8VNRMPzX/BWFZTMDDGFAeJPs9NQixXub1U
    #             aV8L+R0KlCXkJwrXLHadDUpupY5XX/lacyCc38Sk2bO2RkOcmYp51V245vZ0pbCc
    #             tLd9wa9TFdzzsOMDMLa9+BBKhB9cBlvAi3JLo6KcWJScHFG+31ljYhqmMjX7DAMo
    #             p5Guo8L59XahZOsyqhgC8gOd/0CMocBsjDurfTX7v55pQwXWFW0DPVd5e8ynTArz
    #             +5Kj1WC/W8eEGk7BAgMBAAGjTDBKMAwGA1UdEwEB/wQCMAAwOgYDVR0RBDMwMYIQ
    #             bGVhZi5leGFtcGxlLm9yZ4YdaHR0cHM6Ly9leGFtcGxlLmNvbS9PcGVuSUQ0VlAw
    #             DQYJKoZIhvcNAQELBQADggEBACF2aoCODW4tziNQs41C9N363xYPt21uIQy0CQ24
    #             1hRZ8Ev6yIQ/WORfzciLHZsWizZdS3D5oDY7K+WAgMpDSR0Ah9dXMfJjOxcUib57
    #             Zh+YOi443fjU/5/DBHyHgfEvDy1QXXHJuDbgchzAv9u8uY0ibUb/GHy4OKaj9bOI
    #             8g6qgZtT2wkfdHQPX+fpwZueTaHhoXJV+JTuE227fIjLZ5ThbvO0xbE3q4I/v+Gu
    #             ZZ713LQaG2RwdJWTimJUi6Sro5s0YR6qRGejHmiS1FbJOOG4AAE4PkhkxVogItVE
    #             Z4nqCEfD1RT6iwiWyXIYh3cNpWvcE3t4j7e/Su5IhW/Cv2E=
    #             -----END CERTIFICATE-----
    #           - |
    #             -----BEGIN CERTIFICATE-----
    #             MIIDRDCCAiygAwIBAgIUUOBXQmkRjQvfhU1YJbMEOMnPxvQwDQYJKoZIhvcNAQEL
    #             BQAwUjEuMCwGA1UEAwwlQ049Y2EuZXhhbXBsZS5jb20sIE89RXhhbXBsZSBDQSwg
    #             Qz1JVDETMBEGA1UECgwKRXhhbXBsZSBDQTELMAkGA1UEBhMCSVQwHhcNMjUwNDAz
    #             MTU0NzU2WhcNMjYwNDA0MTU0NzU2WjBOMSkwJwYDVQQDDCBodHRwczovL2ludGVy
    #             bWVkaWF0ZS5leGFtcGxlLm5ldDEUMBIGA1UECgwLRXhhbXBsZSBJTlQxCzAJBgNV
    #             BAYTAklUMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsSUAY+mCs1eB
    #             /hWKtF0kncwTRn3jgczjZWmUSSBZT3PzqmD9uqlgEBrv2sOGwO4bBDnutCAHhfnl
    #             2gXifvg2PJHQWu/g1kVY396K+d91nrqQhUabo2cpEca66t7InPMnXkMR5DG6rNP6
    #             l05OLKQIvoTaHzef0rAS4f+5gF7IcRtGq9G8QRnd2lwLmDYRPKY3jp/uvLosOatv
    #             Nx5p2XtxETgOSv4GEtjax3jxkMDIIPrHwTJGWwsGvasEI5lQ/G67OjFZjjSaoJ95
    #             SSPhXoIydmOmXKDN3GY7ZqT9HntuSzyB3GZ4DMLyOdZdvYvt08hUCJnnY0kGhhtW
    #             gW0xb/wyKwIDAQABoxYwFDASBgNVHRMBAf8ECDAGAQH/AgEAMA0GCSqGSIb3DQEB
    #             CwUAA4IBAQBAwwumBWSI/guarZsNd8hEOVZ7dWRQDLxfDZB1jKtgqA2jCEbNGwpY
    #             41NRRfkTi9EfZXXVdbk9xrjNWVsGdDn/Kh/1/b4uatu2ocRG5R3e2KkZMaK1/Ru2
    #             LFP6gvi7i8dvEr8IQqlg+CrEb11CjMXZi36jRZhtSUnUfmUR4hqCN/qzALdiKvHS
    #             NpEu0D6x6l7YEhwtpX7bvWdnEzCUrAUltMPO9pZUR1LBSPTCMSd+vUhJw/84EJEg
    #             D6Lw8OxzYyzSNOrGTqfplqlHrD/WpI6DB6Yq4Rpefz84AWraGVtZbYAlQMyK1EKS
    #             C3Lef0OGQC0anzAXDsGr1As8HdEuSngu
    #             -----END CERTIFICATE-----
    #           - |
    #             -----BEGIN CERTIFICATE-----
    #             MIIDYzCCAkugAwIBAgIUHVMNJD9vqAA4mR+QAJyEQFW4kjQwDQYJKoZIhvcNAQEL
    #             BQAwUjEuMCwGA1UEAwwlQ049Y2EuZXhhbXBsZS5jb20sIE89RXhhbXBsZSBDQSwg
    #             Qz1JVDETMBEGA1UECgwKRXhhbXBsZSBDQTELMAkGA1UEBhMCSVQwHhcNMjUwNDAz
    #             MTU0NzU2WhcNMjYwNDA0MTU0NzU2WjBSMS4wLAYDVQQDDCVDTj1jYS5leGFtcGxl
    #             LmNvbSwgTz1FeGFtcGxlIENBLCBDPUlUMRMwEQYDVQQKDApFeGFtcGxlIENBMQsw
    #             CQYDVQQGEwJJVDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMf3zvlY
    #             zX1DYgv9QjRusMQjSRNdZi72/ydnxO/cAQ1GsgLZ8ewqIL1CnXtIs6i2F8poUOec
    #             g957xk1db6sTqEWXRi5h9IfMUFcd5G7gIbJzjXCiLSVz6m9vZlvqR7BDka1VQhuH
    #             rW2xEIE6+F2lWxJ+crimea/c5VlMKBCh+gQldFq3lTu6smGUz8xl8rhleBPgTgZz
    #             TO4VuVO1dOb/S4lq9twfVYCTznF9vgaNaNh3la7yjzCf+zpSTGQD8TFO8ws1SZRq
    #             O0bkabW8/5XsnwFHLT2LMSPkWMgMD8r+7xef93bvbEy7SA4Hw1Iow2xIIcTDYQ7F
    #             77HQ3OjkogHmhrMCAwEAAaMxMC8wEgYDVR0TAQH/BAgwBgEB/wIBATAZBgNVHREE
    #             EjAQgg5jYS5leGFtcGxlLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEApRUUxw5Dn0wd
    #             lFPApjn7n/SZyx5I1XnOHOIk8aWD0KFFa1zsnONlmRDgC8EQ5XKw3nMUwvnCQUR8
    #             6FmrqP5gINHdqfvWiitC0eQdDhMhIHvdfUMBicgZ0XDVjDZhD6W9A+IWwR3ySLCf
    #             lZHA5JwjYhpAjMYFXwSVZklOre34zJL6CRwgIUKjc9uyGPmlnVRFTUcUqLB9Uq/U
    #             dFc7XMPBAbMt1frOJRj6P1OFtubuC0INpEhzivg3+w8bXmpEN6e2hBvIjoNkgnWF
    #             O6HVbDnJXTA34/I4snisJfZQ+Z9gln921+2Q27sMvyS7aBqtocDuWB0w3XZ3aCYk
    #             DTEzMjUtQA==
    #             -----END CERTIFICATE-----

    #     private_keys: *metadata_jwks

  # Mongodb database configuration
  storage:
    mongo_db:
      cache:
        module: pyeudiw.storage.mongo_cache
        class: MongoCache
        init_params:
          url: mongodb://satosa:thatpassword@satosamongo:27017
          conf:
            db_name: eudiw
          # connection_params:
      storage:
        module: pyeudiw.storage.mongo_storage
        class: MongoStorage
        init_params:
          url: mongodb://satosa:thatpassword@satosamongo:27017
          conf:
            db_name: eudiw
            db_sessions_collection: sessions
            db_trust_attestations_collection: trust_attestations
            db_trust_anchors_collection: trust_anchors
            db_trust_sources_collection: trust_sources
            data_ttl: 63072000 # 2 years
          # - connection_params:
```

The error is encountered at this step of the integration test (the Wallet tries to obtain the request object / JAR jwt)

https://github.com/italia/eudi-wallet-it-python/blob/e2454c5265fee98fd4b9dc5fabcf147fe3cdfa31/example/satosa/integration_test/same_device_integration_test.py#L55

this is the logged exception by the container containing the satosa+pyeudiw environment

```
satosa-saml2spid  | WARNING:pyeudiw.tools.base_logger:[UNKNOWN] Exception encountered when updating metadata with DirectTrustSdJwtVc for issuer IT-RP: Invalid URL 'IT-RP/.well-known/openid-credential-issuer': No scheme supplied. Perhaps you meant https://IT-RP/.well-known/openid-credential-issuer?
satosa-saml2spid  | WARNING:pyeudiw.tools.base_logger:[UNKNOWN] Failed to extract jwks from issuer IT-RP: Connection error: HTTPSConnectionPool(host='it-rp', port=443): Max retries exceeded with url: /.well-known/jwt-vc-issuer (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3fbf81bf50>: Failed to resolve 'it-rp' ([Errno -3] Try again)"))
satosa-saml2spid  | WARNING:pyeudiw.tools.base_logger:[UNKNOWN] Failed to extract jwks from issuer IT-RP: Connection error: HTTPSConnectionPool(host='it-rp', port=443): Max retries exceeded with url: /.well-known/jar-issuer (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3fbe1a3770>: Failed to resolve 'it-rp' ([Errno -3] Try again)"))
satosa-saml2spid  | WARNING:pyeudiw.tools.base_logger:[UNKNOWN] Exception encountered when updating metadata with DirectTrustSdJwtVc for issuer IT-RP: Invalid URL 'IT-RP/.well-known/openid-credential-issuer': No scheme supplied. Perhaps you meant https://IT-RP/.well-known/openid-credential-issuer?
satosa-saml2spid  | WARNING:pyeudiw.tools.base_logger:[UNKNOWN] Failed to extract jwks from issuer IT-RP: Connection error: HTTPSConnectionPool(host='it-rp', port=443): Max retries exceeded with url: /.well-known/jwt-vc-issuer (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3fbe1b6ab0>: Failed to resolve 'it-rp' ([Errno -3] Try again)"))
satosa-saml2spid  | WARNING:pyeudiw.tools.base_logger:[UNKNOWN] Failed to extract jwks from issuer IT-RP: Connection error: HTTPSConnectionPool(host='it-rp', port=443): Max retries exceeded with url: /.well-known/jar-issuer (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3fbe1b6e40>: Failed to resolve 'it-rp' ([Errno -3] Try again)"))
```
